create role anon nologin;
create role authenticated nologin;
create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to anon,authenticated;
grant execute on function auth.uid() to anon,authenticated;
create table public.invoices(id uuid primary key default gen_random_uuid());
create table public.tax_payments(id uuid primary key default gen_random_uuid());
create table public.tax_settings(id uuid primary key default gen_random_uuid());
