export type Fund = {
  id: string;
  system_key: string | null;
  name: string;
  target_amount: number | null;
  target_date: string | null;
  planned_monthly_contribution: number | null;
  priority: number;
  is_active: boolean;
  balance: number;
  progress_percentage: number | null;
  allocations_this_month: number;
  contribution_gap: number;
};
export type Goal = {
  id?: string;
  name: string;
  goal_type: string;
  target_amount: number;
  target_date: string | null;
  linked_fund_id: string | null;
  priority: number;
  status: string;
  current_amount?: number;
  remaining_amount?: number;
  progress_percentage?: number;
  days_remaining?: number | null;
  required_monthly_pace?: number | null;
  linked_fund_name?: string | null;
};
export type Commitment = {
  id?: string;
  name: string;
  commitment_type: string;
  amount: number;
  due_date: string;
  recurrence: string;
  start_date: string;
  end_date: string | null;
  is_essential: boolean;
  status: string;
  note: string | null;
};
export type PlanningSettings = {
  commitments_verified_through: string | null;
  default_safe_to_spend_horizon: number;
  monthly_essential_expenses_target: number | null;
};
export type SafeToSpend = {
  as_of: string;
  horizon_end: string;
  total_liquidity: number;
  reserved_funds_total: number;
  free_liquidity: number;
  required_tax_reserve: number | null;
  tax_fund_balance: number;
  tax_reserve_gap: number | null;
  emergency_fund_balance: number;
  house_fund_balance: number;
  emergency_coverage_months: number | null;
  upcoming_essential_commitments: number;
  upcoming_other_commitments: number;
  emergency_contribution_gap: number;
  goals_contribution_gap: number;
  investment_contribution_gap: number;
  total_planned_contributions: number;
  safe_to_spend_raw: number | null;
  safe_to_spend: number | null;
  funding_shortfall: number | null;
  funds_overallocated: boolean;
  funds_overallocation_amount: number;
  status: "confirmed" | "estimated" | "incomplete";
  missing_fields: string[];
  warnings: string[];
  calculated_at: string;
  funds: Fund[];
};
